### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by minatu2d** [gorogoroyasu/mnist-Grad-CAM#4]
Hi gorogoroyasu.
Thanks your work.

I got following error when run `python mnist.py`:

```python
  File "mnist.py", line 33, in <module>
    m = MM()
  File "mnist-Grad-CAM/mnist_model.py", line 14, in __init__
    self.build_model()
  File "mnist-Grad-CAM/mnist_model.py", line 36, in build_model
    self.g = merge([self.before_soft_max, self.a, self.labels], mode=lambda x: K.gradients(x[0] * x[2], x[1]), output_shape=(self.a.shape))
```

**Comment by gorogoroyasu** [comment]
Thanks for you report, and The `merge` method seems to be deleted.  
#3 seems to be fixing it, so I'll check it later, and merge it.

If you are still interested in the error above, I hope you to tell me your Keras version. 

Thank you.

**Comment by minatu2d** [comment]
Thanks for reply.
I've fixed the same way as you mentioned above. Using `Lambda()` instead of `merge`.

Thanks and best regards.
